#!/usr/bin/env node
// Timings are measured from the new recordings, never inherited from the old cut.
import fs from 'node:fs';
import path from 'node:path';
import {dayDir, ffmpeg, decode, SR} from './body51_day_common.mjs';
import {speechSpans} from './body51_speech.mjs';

const round = n => +n.toFixed(5);
// Globally align sentence boundaries to actual pauses, rather than spreading
// subtitles across wall-clock time. Small pauses within words aren't candidates.
function align(spec, lines, onset, offset, reviewedPauses) {
  const vowels = text => Math.max(1, (text.match(/[аеёиоуыэюя]/gi) || []).length);
  const weights = lines.map(text => vowels(text) + text.split(/\s+/).length * .35);
  const sum = weights.reduce((a, b) => a + b, 0);
  const pauses = spec.pauses.filter(([a, b]) => a > onset + .1 && b < offset - .1 && b - a >= .18);
  const points = [onset, ...pauses.map(([a, b]) => (a + b) / 2), offset];
  if (points.length < lines.length + 1) throw new Error('Not enough speech pauses to align sentences');
  const memo = new Map();
  function solve(line, from) {
    const key = `${line}:${from}`;
    if (memo.has(key)) return memo.get(key);
    if (line === lines.length) return from === points.length - 1 ? {cost: 0, ends: []} : {cost: Infinity};
    let best = {cost: Infinity};
    const expected = weights[line] / sum * (offset - onset);
    for (let to = from + 1; to < points.length; to++) {
      if (points.length - 1 - to < lines.length - 1 - line) continue;
      const next = solve(line + 1, to);
      const length = points[to] - points[from];
      const cost = next.cost + ((length - expected) / Math.max(.65, expected)) ** 2;
      if (cost < best.cost) best = {cost, ends: [to, ...next.ends]};
    }
    memo.set(key, best); return best;
  }
  const solution = reviewedPauses ? {cost: 0, ends: [...reviewedPauses.map(i => i + 1), points.length - 1]} : solve(0, 0);
  if (!Number.isFinite(solution.cost)) throw new Error('Sentence alignment failed');
  let from = onset;
  return lines.map((text, i) => {
    const to = points[solution.ends[i]];
    const result = {text, start: round(from - onset), end: round(to - onset)};
    from = to; return result;
  });
}

const script = JSON.parse(fs.readFileSync(path.join(dayDir, 'script.json'), 'utf8'));
let cursor = 0;
const scenes = script.scenes.map((scene, i) => {
  const file = path.join(dayDir, 'voices', scene.voice + '.mp3');
  const pcm = decode(file);
  const spec = speechSpans(file, {ffmpeg, noise: '-36dB', min: .12});
  // MP3 container duration includes padding. Use decoded samples, not the
  // rounded ffmpeg "Duration" field (which creates phantom final speech spans).
  const actual = pcm.length / SR;
  let onset = spec.onset;
  let offset = actual;
  const ending = spec.pauses.find(([a, b]) => a > actual - .7 && b >= actual - .055);
  if (ending) offset = ending[0];
  const lead = i === 0 ? .28 : .22;
  const tail = i === script.scenes.length - 1 ? 1.35 : .27;
  const speech = offset - onset;
  const dur = Math.ceil((lead + speech + tail) * script.format.fps) / script.format.fps;
  const captions = align(spec, scene.lines, onset, offset, scene.sentencePauses).map(c => ({...c, start: round(c.start + lead), end: round(c.end + lead)}));
  const result = {...scene, index: i, start: round(cursor), duration: round(dur), lead, trimIn: round(onset), trimOut: round(offset), speech: round(speech), captions};
  cursor += dur;
  console.log(`${scene.id.padEnd(9)} ${result.start.toFixed(2)}–${cursor.toFixed(2)}s · ${scene.voice}`);
  for (const c of captions) console.log(`  ${c.start.toFixed(2)}–${c.end.toFixed(2)}  ${c.text}`);
  return result;
});
const data = {...script, scenes, total: round(cursor), audio: 'soundtrack.m4a', version: script.version || 'day-1'};
const outputDir = process.env.BODY51_DAY_BUILD_DIR || dayDir;
fs.mkdirSync(outputDir, {recursive: true});
fs.writeFileSync(path.join(outputDir, 'timeline.json'), JSON.stringify(data, null, 2) + '\n');
fs.writeFileSync(path.join(outputDir, 'timeline.js'), '// Generated by tools/build_body51_day.mjs. Do not edit.\nwindow.BODY51_DAY = ' + JSON.stringify(data, null, 2) + ';\n');
function time(t) {
  const ms = Math.round(t * 1000);
  return `${String(Math.floor(ms / 3600000)).padStart(2, '0')}:${String(Math.floor(ms / 60000) % 60).padStart(2, '0')}:${String(Math.floor(ms / 1000) % 60).padStart(2, '0')}.${String(ms % 1000).padStart(3, '0')}`;
}
fs.writeFileSync(path.join(outputDir, 'captions.vtt'), 'WEBVTT\n\n' + scenes.flatMap(s => s.captions.map(c => `${time(s.start + c.start)} --> ${time(s.start + c.end)}\n${c.text}\n`)).join('\n'));
console.log(`New film: ${data.total.toFixed(2)}s · ${data.format.width}×${data.format.height} · ${data.format.fps}fps`);
